### PR TITLE
Institution loader

### LINKED ISSUE #3142: Fix institution loader parser
Institution loader parser fails when the hmda_filer flag is 't'.

### PR DESCRIPTION
**Pull request by omnipresent07**
Closes #3142

### CODE REVIEW

File: common/src/main/scala/hmda/parser/institution/InstitutionCsvParser.scala [hunk 1]
```diff
@@ -42,17 +42,22 @@ object InstitutionCsvParser {
...
-      ),
+      Parent(parentIdRssd, if (parentName == "") None else Some(parentName)),
       assets,
       otherLenderCode,
       TopHolder(
         topHolderIdRssd,
         if (topHolderName == "") None else Some(topHolderName)
       ),
-      if (hmdaFiler == "") false else hmdaFiler.toBoolean
+      if (hmdaFiler == "") false
```
Comment (BarakStout) [inline common/src/main/scala/hmda/parser/institution/InstitutionCsvParser.scala]: Do we need the if ?
