### PR TITLE
Fix RejectedExecutionException in Specs

### LINKED ISSUE #914: PublicHttpApiSpec failing in Jenkins
I am consistently getting the following failure while running the test suite in Jenkins.  I do not get this error when I run the test suite locally.  It sounds like we've also seen this pop up in Travis.

```
[info] hmda.api.http.public.PublicHttpApiSpec *** ABORTED ***
[info]   java.util.concurrent.RejectedExecutionException: Task slick.basic.BasicBackend$DatabaseDef$$anon$2@562359f5 rejected from 
slick.util.AsyncExecutor$$anon$2$$anon$1@5d9eee39[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 71]
[info]   at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
[info]   at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
[info]   at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
[info]   at slick.util.AsyncExecutor$$anon$2$$anon$3.execute(AsyncExecutor.scala:120)
[info]   at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction(BasicBackend.scala:233)
[info]   at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction$(BasicBackend.scala:231)
[info]   at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:38)
[info]   at slick.basic.BasicBackend$DatabaseDef.runInContext(BasicBackend.scala:210)
[info]   at slick.basic.BasicBackend$DatabaseDef.runInContext$(BasicBackend.scala:142)
[info]   at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:38)
[info]   ...
```

### PR DESCRIPTION
**Pull request by schbetsy**
Closes #914 . The tests now pass in Jenkins; ask me for the link if you want to see.

Bonus: This allows us to fully test the IRS Path again.

### CODE REVIEW

File: api/src/test/scala/hmda/api/http/institutions/UploadPathsSpec.scala [hunk 1]
```diff
@@ -38,24 +37,27 @@ class UploadPathsSpec extends InstitutionHttpApiAsyncSpec with SubmissionProtoco
...
+      _ <- repository.createSchema()
+      c <- modifiedLarRepository.createSchema()
+    } yield c
+    Await.result(setup, duration)
   }
 
   override def afterAll(): Unit = {
     super.afterAll()
-    dropAllObjects()
-    repository.config.db.close()
```
Comment (schbetsy) [inline api/src/test/scala/hmda/api/http/institutions/UploadPathsSpec.scala]: FYI, for those interested: This was the line that was causing the errors. This test would close the db, then any specs that ran after this one wouldn't be able to connect to it.

Comment (nickgrippin) [inline api/src/test/scala/hmda/api/http/institutions/UploadPathsSpec.scala]: Dang, awesome catch!!! 👍
