### PR TITLE
Remove test banks regulator data

### LINKED ISSUE #1411: Investigate and correct regulator data export formatting issues
For release 1.21 perhaps.. The following items have been reported in regards to the current regulator data export:

- [ ] Data in incorrect fields in the panel file:  
> the data in “email_domain_3” column should be in “respondent_name” column and so forth. The data in “parent_state” and “assets” columns should come from “'parent_city” column then you will have to split the text if there are 2 letters state abbreviation.

- [ ] Investigate panel data issues (could be related to the above): 

Missing fields?: 
•         id_rssd (RSSDID)
•         p_rssd (Parent RSSDID)

Corrections:  
*  Institution_Type should be institution type code but is showing institution type description

### LINKED ISSUE #1422: Prevent Bank 0 and Bank 1 data from being written to S3
Prevent Bank 0 and Bank 1 data in prod from being written to S3 and therefore transferred to other regulators.

### PR DESCRIPTION
**Pull request by jmarin**
Closes #1411 (item #4, lower priority, not included)
Closes #1422

### CODE REVIEW

File: publication/src/main/scala/hmda/publication/regulator/lar/RegulatorLarPublisher.scala [hunk 1]
```diff
@@ -66,57 +68,18 @@ class RegulatorLarPublisher extends HmdaActor with LoanApplicationRegisterCassan
...
-            "denial3|" +
-            "rate_spread|" +
-            "hoepa_status|" +
-            "lien_status\n"
-        ).toIterator).map(s => ByteString(s))
-
-      val larSource = readData(fetchSize)
+      val source = readData(fetchSize)
+        .via(filterTestBanks)
         .map(lar => lar.toCSV + "\n")
```
Comment (schbetsy) [inline publication/src/main/scala/hmda/publication/regulator/lar/RegulatorLarPublisher.scala]: When I test this by sinking the data into a local file instead of to S3, it produces a file like this:

```
2|0|1|10665|20170307|1|1|2|2|44|3|3|20170311|45460|18|167|0102.01|2|5|5|||||8|||||2|5|24|0|1|||NA|2|1

2|0|1|10654|20170307|1|1|2|1|32|3|1|20170418|45460|18|021|0403.00|2|5|5|||||8|||||2|5|25|0||||NA|2|1

2|0|1|10855|20170311|1|1|3|1|24|3|1|20170414|45460|18|167|0014.00|2|2|5|||||5|||||1|2|60|0||||NA|2|2

2|0|1|10831|20170310|1|1|3|1|8|3|1|20170410|NA|17|191|9552.00|2|2|5|||||5|||||1|2|37|0||||NA|2|1

2|0|1|10531|20170304|1|1|2|1|43|3|4|20170723|45460|18|165|0205.00|2|5|5|||||8|||||1|5|23|0||||NA|2|1
```

with an extra blank line between each csv line. Does it also do that in s3?

Comment (jmarin) [reply publication/src/main/scala/hmda/publication/regulator/lar/RegulatorLarPublisher.scala]: Did you see this in any of the files in `S3`?. I just randomly checked 3 of the files being delivered to the production environment and their structure is fine.
