### PR TITLE
Disclosure 11-1 through 11-10

### LINKED ISSUE #1249: Table 11-1: Disclosure by Respondent ID
**Table 11-1**: "PRICING INFORMATION FOR FHA HOME-PURCHASE LOANS, FIRST LIEN, 1- TO 4-FAMILY OWNER-OCCUPIED DWELLING (EXCLUDES MANUFACTURED HOMES), BY BORROWER OR CENSUS TRACT CHARACTERISTICS"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`respondent_id`
`institution_name`
`table:` "11-1"
`type:` "Disclosure"
`desc:` "Pricing information for FHA home-purchase loans, first lien, 1- to 4-family owner-occupied dwelling (excludes manufactured homes), by borrower or census tract characteristics"
`year`
`report-date`
`msa`
`applicantincomes`

JSON*: [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-1/11-1.json)
Prototype: None created, see FFIEC Report attached below
*note: example is an Aggregate report; also uses term "Census Characteristics", which should be "Census Tract Characteristics"

[2016HD11-1_0000112837910780.pdf](https://github.com/cfpb/hmda-platform/files/1414936/2016HD11-1_0000112837910780.pdf)

## Overall table filters
Loan Type: 2
Purpose of Loan: 1
Lien Status: 1
Property Type: 1
Owner-Occupancy: 1

## Borrower or Census Tract Characteristics

**Borrower Characteristics**
•	[Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization)
•	[Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization)
•	[Minority Status](https://github.com/cfpb/hmda-platform/wiki/Minority-Status-Categorization)
•	[Gender](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Census Tract Characteristics**
•	[Racial/Ethnic Composition](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Dispositions
This table includes the following dispositions:
•	[No Reported Pricing Data](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	Reported Pricing Data
•	1.50 - 1.99*
•	2.00 - 2.49*
•	2.50 - 2.99*
•	3.00 - 3.99*
•	4.00 - 4.99*
•	5 or more*
•	Mean*
•	Median*
•	[HOEPA Loans](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

*note: included in broader category of [PERCENTAGE POINTS ABOVE AVERAGE PRIME OFFER RATE: ONLY INCLUDES LOANS WITH APR ABOVE THE THRESHOLD](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

### LINKED ISSUE #1252: Table 11-2: Disclosure by Respondent ID
**Table 11-2**: "PRICING INFORMATION FOR VA HOME-PURCHASE LOANS, FIRST LIEN, 1- TO 4-FAMILY OWNER-OCCUPIED DWELLING (EXCLUDES MANUFACTURED HOMES), BY BORROWER OR CENSUS TRACT CHARACTERISTICS"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`respondent_id`
`institution_name`
`table:` "11-2"
`type:` "Disclosure"
`desc:` "Pricing information for VA home-purchase loans, first lien, 1- to 4-family owner-occupied dwelling (excludes manufactured homes), by borrower or census tract characteristics"
`year`
`report-date`
`msa`
`applicantincomes`

JSON*: [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-2/11-2.json)
Prototype: None created, see FFIEC Report attached below
*note: example is an Aggregate report; also uses term "Census Characteristics", which should be "Census Tract Characteristics"

[2016HD11-2_0000451965916740.pdf](https://github.com/cfpb/hmda-platform/files/1415022/2016HD11-2_0000451965916740.pdf)

## Overall table filters
Loan Type: 3
Purpose of Loan: 1
Lien Status: 1
Property Type: 1
Owner-Occupancy: 1

## Borrower or Census Tract Characteristics

**Borrower Characteristics**
•	[Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization)
•	[Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization)
•	[Minority Status](https://github.com/cfpb/hmda-platform/wiki/Minority-Status-Categorization)
•	[Gender](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Census Tract Characteristics**
•	[Racial/Ethnic Composition](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Dispositions
This table includes the following dispositions:
•	[No Reported Pricing Data](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	Reported Pricing Data
•	1.50 - 1.99*
•	2.00 - 2.49*
•	2.50 - 2.99*
•	3.00 - 3.99*
•	4.00 - 4.99*
•	5 or more*
•	Mean*
•	Median*
•	[HOEPA Loans](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

*note: included in broader category of [PERCENTAGE POINTS ABOVE AVERAGE PRIME OFFER RATE: ONLY INCLUDES LOANS WITH APR ABOVE THE THRESHOLD](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

### LINKED ISSUE #1255: Table 11-3: Disclosure by Respondent ID
**Table 11-3**: "PRICING INFORMATION FOR CONVENTIONAL HOME-PURCHASE LOANS, FIRST LIEN, 1- TO 4-FAMILY OWNER-OCCUPIED DWELLING (EXCLUDES MANUFACTURED HOMES), BY BORROWER OR CENSUS TRACT CHARACTERISTICS,"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`respondent_id`
`institution_name`
`table:` "11-3"
`type:` "Disclosure"
`desc:` "Pricing information for conventional home-purchase loans, first lien, 1- to 4-family owner-occupied dwelling (excludes manufactured homes), by borrower or census tract characteristics"
`year`
`report-date`
`msa`
`applicantincomes`

JSON*: [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-3/11-3.json)
Prototype: None created, see FFIEC Report attached below
*note: example is an Aggregate report; also uses term "Census Characteristics", which should be "Census Tract Characteristics"

[2016HD11-3_0000451965916740.pdf](https://github.com/cfpb/hmda-platform/files/1415115/2016HD11-3_0000451965916740.pdf)

## Overall table filters
Loan Type: 1
Purpose of Loan: 1
Lien Status: 1
Property Type: 1
Owner-Occupancy: 1

## Borrower or Census Tract Characteristics

**Borrower Characteristics**
•	[Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization)
•	[Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization)
•	[Minority Status](https://github.com/cfpb/hmda-platform/wiki/Minority-Status-Categorization)
•	[Gender](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Census Tract Characteristics**
•	[Racial/Ethnic Composition](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Dispositions
This table includes the following dispositions:
•	[No Reported Pricing Data](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	Reported Pricing Data
•	1.50 - 1.99*
•	2.00 - 2.49*
•	2.50 - 2.99*
•	3.00 - 3.99*
•	4.00 - 4.99*
•	5 or more*
•	Mean*
•	Median*
•	[HOEPA Loans](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

*note: included in broader category of [PERCENTAGE POINTS ABOVE AVERAGE PRIME OFFER RATE: ONLY INCLUDES LOANS WITH APR ABOVE THE THRESHOLD](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

### LINKED ISSUE #1258: Table 11-4: Disclosure by Respondent ID
**Table 11-4**: "PRICING INFORMATION FOR CONVENTIONAL HOME-PURCHASE LOANS, JUNIOR LIEN, 1- TO 4-FAMILY OWNER-OCCUPIED DWELLING (EXCLUDES MANUFACTURED HOMES), BY BORROWER OR CENSUS TRACT CHARACTERISTICS,"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`respondent_id`
`institution_name`
`table:` "11-4"
`type:` "Disclosure"
`desc:` "Pricing information for conventional home-purchase loans, junior lien, 1- to 4-family owner-occupied dwelling (excludes manufactured homes), by borrower or census tract characteristics"
`year`
`report-date`
`msa`
`applicantincomes`

JSON*: [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-4/11-4.json)
Prototype: None created, see FFIEC Report attached below
*note: example is an Aggregate report;  uses term "Census Characteristics", which should be "Census Tract Characteristics; also has incorrect pricing information - refer to FFIEC Report or dispositions outlined below for the correct information

[2016HD11-4_0000451965916740.pdf](https://github.com/cfpb/hmda-platform/files/1415329/2016HD11-4_0000451965916740.pdf)

## Overall table filters
Loan Type: 1
Purpose of Loan: 1
Lien Status: 2
Property Type: 1
Owner-Occupancy: 1

## Borrower or Census Tract Characteristics

**Borrower Characteristics**
•	[Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization)
•	[Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization)
•	[Minority Status](https://github.com/cfpb/hmda-platform/wiki/Minority-Status-Categorization)
•	[Gender](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Census Tract Characteristics**
•	[Racial/Ethnic Composition](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Dispositions
This table includes the following dispositions:
•	[No Reported Pricing Data](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	Reported Pricing Data
•	3.50 - 3.99*
•	4.00 - 4.49*
•	4.50 - 4.99*
•	5.00 - 5.99*
•	6.00 - 6.99*
•	7 or more*
•	Mean*
•	Median*
•	[HOEPA Loans](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

*note: included in broader category of [PERCENTAGE POINTS ABOVE AVERAGE PRIME OFFER RATE: ONLY INCLUDES LOANS WITH APR ABOVE THE THRESHOLD](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

### LINKED ISSUE #1261: Table 11-5: Disclosure by Respondent ID
**Table 11-5**: "PRICING INFORMATION FOR FHA REFINANCING LOANS, FIRST LIEN, 1- TO 4-FAMILY OWNER-OCCUPIED DWELLING (EXCLUDES MANUFACTURED HOMES), BY BORROWER OR CENSUS TRACT CHARACTERISTICS,"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`respondent_id`
`institution_name`
`table:` "11-5"
`type:` "Disclosure"
`desc:` "Pricing information for FHA refinancing loans, first lien, 1- to 4-family owner-occupied dwelling (excludes manufactured homes), by borrower or census tract characteristics"
`year`
`report-date`
`msa`
`applicantincomes`

JSON*: [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-5/11-5.json)
Prototype: None created, see FFIEC Report attached below
*note: example is an Aggregate report; also uses term "Census Characteristics", which should be "Census Tract Characteristics

[2016HD11-5_0000451965916740.pdf](https://github.com/cfpb/hmda-platform/files/1415414/2016HD11-5_0000451965916740.pdf)

## Overall table filters
Loan Type: 2
Purpose of Loan: 3
Lien Status: 1
Property Type: 1
Owner-Occupancy: 1

## Borrower or Census Tract Characteristics

**Borrower Characteristics**
•	[Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization)
•	[Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization)
•	[Minority Status](https://github.com/cfpb/hmda-platform/wiki/Minority-Status-Categorization)
•	[Gender](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Census Tract Characteristics**
•	[Racial/Ethnic Composition](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Dispositions
This table includes the following dispositions:
•	[No Reported Pricing Data](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	Reported Pricing Data
•	1.50 - 1.99*
•	2.00 - 2.49*
•	2.50 - 2.99*
•	3.00 - 3.99*
•	4.00 - 4.99*
•	5 or more*
•	Mean*
•	Median*
•	[HOEPA Loans](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

*note: included in broader category of [PERCENTAGE POINTS ABOVE AVERAGE PRIME OFFER RATE: ONLY INCLUDES LOANS WITH APR ABOVE THE THRESHOLD](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

### LINKED ISSUE #1264: Table 11-6: Disclosure by Respondent ID
**Table 11-6**: "PRICING INFORMATION FOR VA REFINANCING LOANS, FIRST LIEN, 1- TO 4-FAMILY OWNER-OCCUPIED DWELLING (EXCLUDES MANUFACTURED HOMES), BY BORROWER
OR CENSUS TRACT CHARACTERISTICS"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`respondent_id`
`institution_name`
`table:` "11-6"
`type:` "Disclosure"
`desc:` "Pricing information for VA refinancing loans, first lien, 1- to 4-family owner-occupied dwelling (excludes manufactured homes), by borrower or census tract characteristics"
`year`
`report-date`
`msa`
`applicantincomes`

JSON*: [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-6/11-6.json)
Prototype: None created, see FFIEC Report attached below
*note: example is an Aggregate report; also uses term "Census Characteristics", which should be "Census Tract Characteristics

[2016HN11-6_________________.pdf](https://github.com/cfpb/hmda-platform/files/1415552/2016HN11-6_________________.pdf)

## Overall table filters
Loan Type: 3
Purpose of Loan: 3
Lien Status: 1
Property Type: 1
Owner-Occupancy: 1

**Borrower Characteristics**
•	[Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization)
•	[Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization)
•	[Minority Status](https://github.com/cfpb/hmda-platform/wiki/Minority-Status-Categorization)
•	[Gender](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Census Tract Characteristics**
•	[Racial/Ethnic Composition](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Dispositions
This table includes the following dispositions:
•	[No Reported Pricing Data](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	Reported Pricing Data
•	1.50 - 1.99*
•	2.00 - 2.49*
•	2.50 - 2.99*
•	3.00 - 3.99*
•	4.00 - 4.99*
•	5 or more*
•	Mean*
•	Median*
•	[HOEPA Loans](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

*note: included in broader category of [PERCENTAGE POINTS ABOVE AVERAGE PRIME OFFER RATE: ONLY INCLUDES LOANS WITH APR ABOVE THE THRESHOLD](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

### LINKED ISSUE #1267: Table 11-7: Disclosure by Respondent ID
**Table 11-7**: "PRICING INFORMATION FOR CONVENTIONAL REFINANCING LOANS, FIRST LIEN, 1- TO 4-FAMILY OWNER-OCCUPIED DWELLING (EXCLUDES MANUFACTURED HOMES), BY BORROWER OR CENSUS TRACT CHARACTERISTICS"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`respondent_id`
`institution_name`
`table:` "11-7"
`type:` "Disclosure"
`desc:` "Pricing information for conventional refinancing loans, first lien, 1- to 4-family owner-occupied dwelling (excludes manufactured homes), by borrower or census tract characteristics"
`year`
`report-date`
`msa`
`applicantincomes`

JSON*: [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-7/11-7.json)
Prototype: None created, see FFIEC Report attached below
*note: example is an Aggregate report; also uses term "Census Characteristics", which should be "Census Tract Characteristics

[2016HD11-7_0000451965916740.pdf](https://github.com/cfpb/hmda-platform/files/1415954/2016HD11-7_0000451965916740.pdf)

## Overall table filters
Loan Type: 1
Purpose of Loan: 3
Lien Status: 1
Property Type: 1
Owner-Occupancy: 1

## Borrower or Census Tract Characteristics

**Borrower Characteristics**
•	[Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization)
•	[Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization)
•	[Minority Status](https://github.com/cfpb/hmda-platform/wiki/Minority-Status-Categorization)
•	[Gender](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Census Tract Characteristics**
•	[Racial/Ethnic Composition](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Dispositions
This table includes the following dispositions:
•	[No Reported Pricing Data](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	Reported Pricing Data
•	1.50 - 1.99*
•	2.00 - 2.49*
•	2.50 - 2.99*
•	3.00 - 3.99*
•	4.00 - 4.99*
•	5 or more*
•	Mean*
•	Median*
•	[HOEPA Loans](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

*note: included in broader category of [PERCENTAGE POINTS ABOVE AVERAGE PRIME OFFER RATE: ONLY INCLUDES LOANS WITH APR ABOVE THE THRESHOLD](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

### LINKED ISSUE #1270: Table 11-8: Disclosure by Respondent ID
**Table 11-8**: "PRICING INFORMATION FOR CONVENTIONAL REFINANCING LOANS, JUNIOR LIEN, 1- TO 4-FAMILY OWNER-OCCUPIED DWELLING (EXCLUDES MANUFACTURED HOMES), BY BORROWER OR CENSUS TRACT CHARACTERISTICS"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`respondent_id`
`institution_name`
`table:` "11-8"
`type:` "Disclosure"
`desc:` "Pricing information for conventional refinancing loans, junior lien, 1- to 4-family owner-occupied dwelling (excludes manufactured homes), by borrower or census tract characteristics"
`year`
`report-date`
`msa`
`applicantincomes`

JSON*: [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-8/11-8.json)
Prototype: None created, see FFIEC Report attached below (
*note: example is an Aggregate report; uses term "Census Characteristics", which should be "Census Tract Characteristics; also has incorrect table description and pricing information - refer to FFIEC Report for the correct information

[2016HD11-8_0000480228916740.pdf](https://github.com/cfpb/hmda-platform/files/1416046/2016HD11-8_0000480228916740.pdf)

## Overall table filters
Loan Type: 1
Purpose of Loan: 3
Lien Status: 2
Property Type: 1
Owner-Occupancy: 1

## Borrower or Census Tract Characteristics

**Borrower Characteristics**
•	[Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization)
•	[Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization)
•	[Minority Status](https://github.com/cfpb/hmda-platform/wiki/Minority-Status-Categorization)
•	[Gender](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Census Tract Characteristics**
•	[Racial/Ethnic Composition](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Dispositions
This table includes the following dispositions:
•	[No Reported Pricing Data](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	Reported Pricing Data
•	3.50 - 3.99*
•	4.00 - 4.49*
•	4.50 - 4.99*
•	5.00 - 5.99*
•	6.00 - 6.99*
•	7 or more*
•	Mean*
•	Median*
•	[HOEPA Loans](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

*note: included in broader category of [PERCENTAGE POINTS ABOVE AVERAGE PRIME OFFER RATE: ONLY INCLUDES LOANS WITH APR ABOVE THE THRESHOLD](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

### LINKED ISSUE #1273: Table 11-9: Disclosure by Respondent ID
**Table 11-9**: "PRICING INFORMATION FOR CONVENTIONAL HOME IMPROVEMENT LOANS, FIRST LIEN, 1- TO 4-FAMILY OWNER-OCCUPIED DWELLING (EXCLUDES MANUFACTURED HOMES), BY BORROWER OR CENSUS TRACT CHARACTERISTICS"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`respondent_id`
`institution_name`
`table:` "11-9"
`type:` "Disclosure"
`desc:` "Pricing information for conventional home improvement loans, first lien, 1- to 4-family owner-occupied dwelling (excludes manufactured homes), by borrower or census tract characteristics"
`year`
`report-date`
`msa`
`applicantincomes`

JSON*: [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-9/11-9.json)
Prototype: None created, see FFIEC Report attached below
*note: example is an Aggregate report; also uses term "Census Characteristics", which should be "Census Tract Characteristics

[2016HD11-9_0000112837910780.pdf](https://github.com/cfpb/hmda-platform/files/1416076/2016HD11-9_0000112837910780.pdf)

## Overall table filters
Loan Type: 1
Purpose of Loan: 2
Lien Status: 1
Property Type: 1
Owner-Occupancy: 1

## Borrower or Census Tract Characteristics

**Borrower Characteristics**
•	[Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization)
•	[Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization)
•	[Minority Status](https://github.com/cfpb/hmda-platform/wiki/Minority-Status-Categorization)
•	[Gender](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Census Tract Characteristics**
•	[Racial/Ethnic Composition](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Dispositions
This table includes the following dispositions:
•	[No Reported Pricing Data](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	Reported Pricing Data
•	1.50 - 1.99*
•	2.00 - 2.49*
•	2.50 - 2.99*
•	3.00 - 3.99*
•	4.00 - 4.99*
•	5 or more*
•	Mean*
•	Median*
•	[HOEPA Loans](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

*note: included in broader category of [PERCENTAGE POINTS ABOVE AVERAGE PRIME OFFER RATE: ONLY INCLUDES LOANS WITH APR ABOVE THE THRESHOLD](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

### LINKED ISSUE #1276: Table 11-10: Disclosure by Respondent ID
**Table 11-10**: "PRICING INFORMATION FOR CONVENTIONAL HOME IMPROVEMENT LOANS, JUNIOR LIEN, 1- TO 4-FAMILY OWNER-OCCUPIED DWELLING (EXCLUDES MANUFACTURED HOMES), BY BORROWER OR CENSUS TRACT CHARACTERISTICS"

## Report Structure
Data model: [here](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports-data-model)

`respondent_id`
`institution_name`
`table:` "11-10"
`type:` "Disclosure"
`desc:` "Pricing information for conventional home improvement loans, junior lien, 1- to 4-family owner-occupied dwelling (excludes manufactured homes), by borrower or census tract characteristics"
`year`
`report-date`
`msa`
`applicantincomes`

JSON*: [here](https://github.com/cfpb/hmda-viz-prototype/blob/gh-pages/aggregate/2013/alabama/decatur/11-10/11-10.json)
Prototype: None created, see FFIEC Report attached below
*note: example is an Aggregate report; uses term "Census Characteristics", which should be "Census Tract Characteristics; also has incorrect table description and pricing information - refer to FFIEC Report for the correct information

[2016HD11-100000112837935380.pdf](https://github.com/cfpb/hmda-platform/files/1418537/2016HD11-100000112837935380.pdf)

## Overall table filters
Loan Type: 1
Purpose of Loan: 2
Lien Status: 2
Property Type: 1
Owner-Occupancy: 1

## Borrower or Census Tract Characteristics

**Borrower Characteristics**
•	[Race](https://github.com/cfpb/hmda-platform/wiki/Race-Categorization)
•	[Ethnicity](https://github.com/cfpb/hmda-platform/wiki/Ethnicity-Categorization)
•	[Minority Status](https://github.com/cfpb/hmda-platform/wiki/Minority-Status-Categorization)
•	[Gender](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

**Census Tract Characteristics**
•	[Racial/Ethnic Composition](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	[Income](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Dispositions
This table includes the following dispositions:
•	[No Reported Pricing Data](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)
•	Reported Pricing Data
•	3.50 - 3.99*
•	4.00 - 4.49*
•	4.50 - 4.99*
•	5.00 - 5.99*
•	6.00 - 6.99*
•	7 or more*
•	Mean*
•	Median*
•	[HOEPA Loans](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

*note: included in broader category of [PERCENTAGE POINTS ABOVE AVERAGE PRIME OFFER RATE: ONLY INCLUDES LOANS WITH APR ABOVE THE THRESHOLD](https://github.com/cfpb/hmda-platform/wiki/A&D-Reports---Explanatory-Notes)

## Types of A&D Reports
[Here](https://github.com/cfpb/hmda-platform/wiki/Types-of-A&D-reports)

### LINKED ISSUE #1355: A&D Report function `calculateYear` fails if there are no lars
[The `calculateYear` method](https://github.com/cfpb/hmda-platform/blob/fcfee58d6e034fe2c3abc53d67cc6116f79d3f21/publication/src/main/scala/hmda/publication/reports/util/ReportUtil.scala#L135) throws an error if `larSource` is empty.

This is because [the method it relies on](https://github.com/cfpb/hmda-platform/blob/fcfee58d6e034fe2c3abc53d67cc6116f79d3f21/persistence-model/src/main/scala/hmda/util/SourceUtils.scala#L20), `collectHeadValue`, uses `xs.head` without checking whether there are any contents .

It results in a kind of confusing error:
```
[info]   java.lang.UnsupportedOperationException: empty.head
[info]   at scala.collection.immutable.Vector.head(Vector.scala:185)
[info]   at hmda.util.SourceUtils.$anonfun$collectHeadValue$1(SourceUtils.scala:20)
[info]   at hmda.util.SourceUtils$$Lambda$2623/187018820.apply(Unknown Source)
[info]   at scala.util.Success.$anonfun$map$1(Try.scala:251)
[info]   at scala.util.Success.map(Try.scala:209)
[info]   at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
[info]   at scala.concurrent.Future$$Lambda$2315/491500999.apply(Unknown Source)
[info]   at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
[info]   at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
[info]   at scala.concurrent.impl.Promise$$Lambda$2186/2118852835.apply(Unknown Source)
```

Update the method(s) so that they fail gracefully without stopping execution.

### LINKED ISSUE #1376: Disclosure 11-1 through 11-10
- [ ] #1249 (Disclosure 11-1)
 - [ ] #1252 (Disclosure 11-2)
 - [ ] #1255 (Disclosure 11-3)
 - [ ] #1258 (Disclosure 11-4)
 - [ ] #1261 (Disclosure 11-5)
 - [ ] #1264 (Disclosure 11-6)
 - [ ] #1267 (Disclosure 11-7)
 - [ ] #1270 (Disclosure 11-8)
 - [ ] #1273 (Disclosure 11-9)
 - [ ] #1276 (Disclosure 11-10)

### PR DESCRIPTION
**Pull request by schbetsy**
Closes #1376 (Combined 11-1 through 11-10 ticket)
Closes #1249 (Disclosure 11-1)
Closes #1252 (Disclosure 11-2)
Closes #1255 (Disclosure 11-3)
Closes #1258 (Disclosure 11-4)
Closes #1261 (Disclosure 11-5)
Closes #1264 (Disclosure 11-6)
Closes #1267 (Disclosure 11-7)
Closes #1270 (Disclosure 11-8)
Closes #1273 (Disclosure 11-9)
Closes #1276 (Disclosure 11-10)

Closes #1355

### CODE REVIEW

File: publication/src/main/scala/hmda/publication/reports/util/PricingDataUtil.scala [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+         |    "value": "None"
+         |}
+       """.stripMargin
+    }
+  }
+
+  private def reportedMedian[ec: EC, mat: MAT, as: AS](lars: Source[LoanApplicationRegister, NotUsed]): Future[String] = {
+    val rateSpreadsF: Future[Seq[Double]] =
+      lars.filter(pricingDataReported)
+        // .limit(MAX_SIZE)
```
Comment (nickgrippin) [inline publication/src/main/scala/hmda/publication/reports/util/PricingDataUtil.scala]: Is this needed at all?  Just want to make sure it's meant to be commented out.

Comment (schbetsy) [reply publication/src/main/scala/hmda/publication/reports/util/PricingDataUtil.scala]: Oh yeah. I've been thinking about that (thanks for the reminder). I think we should leave it commented unless we experience issues with that method.

It exists to make sure that converting a `Source` to a `Seq` doesn't overflow app memory, but the sets of LARs that actually get sent to that method are going to be pretty small. If anyone feels strongly that we should have it, I'll have to do a little research into what value to set `MAX_SIZE` to.
