### PR TITLE
Fix exhaustive match

### LINKED ISSUE #2175: Match not exhaustive on InstitutionState
The compiler complains about a non exhaustive match on `InstitutionState`

### PR DESCRIPTION
**Pull request by omnipresent07**
fix #2175

### CODE REVIEW

File: hmda/src/main/scala/hmda/persistence/institution/InstitutionState.scala [hunk 1]
```diff
@@ -19,6 +19,7 @@ case class InstitutionState(institution: Option[Institution],
         } else {
           InstitutionState(this.institution, filing :: filings)
         }
+      case _ => this
```
Comment (PatrickHSI) [inline hmda/src/main/scala/hmda/persistence/institution/InstitutionState.scala]: Should we be swallowing all other match cases or logging that they occurred with an event?
