### PR TITLE
Stripped down standard error response

### LINKED ISSUE #433: Create standard error response format for the API
We'll need to create a standardized error response format so API consumers can react appropriately when things go wrong (eg, the front-end displays an error message). Will aid in addressing @schbetsy's observations [here](https://github.com/cfpb/hmda-platform/pull/422#discussion_r69803115) and [here](https://github.com/cfpb/hmda-platform/pull/422#discussion_r69805519)

Minimal example/starting point:

```
{
  path: <uri being requested>,
  code: <403 | 404 | 500 | etc>,
  message: <descriptive error message>
}
```

(`path` and `code` are redundant but convenient).

### PR DESCRIPTION
**Pull request by kgudel**
Create an error response object and protocol to convert it into json and use that in place of only return status codes.

Closes #433

### CODE REVIEW

File: api/src/main/scala/hmda/api/model/ErrorResponse.scala [hunk 1]
```diff
@@ -0,0 +1,7 @@
+package hmda.api.model
+
+case class ErrorResponse(
+  httpStatus: Int,
+  message: String,
+  parth: String
```
Comment (jmarin) [inline api/src/main/scala/hmda/api/model/ErrorResponse.scala]: I think you meant "path" here?

**Comment by jmarin** [comment]
LGTM

File: api/src/test/scala/hmda/api/http/InstitutionsHttpApiSpec.scala [hunk 2]
```diff
@@ -73,9 +74,11 @@ class InstitutionsHttpApiSpec extends WordSpec with MustMatchers with ScalatestR
       }
       Get("/institutions/12345/filings/xxxx") ~> institutionsRoutes ~> check {
         status mustBe StatusCodes.NotFound
+        responseAs[ErrorResponse] mustBe ErrorResponse(404, "xxxx filing not found for institution 12345", "institutions/12345/filings/xxxx")
       }
       Get("/institutions/xxxxx/filings/2017") ~> institutionsRoutes ~> check {
         status mustBe StatusCodes.NotFound
+        responseAs[ErrorResponse] mustBe ErrorResponse(404, "2017 filing not found for institution xxxxx", "institutions/xxxxx/filings/2017")
```
Comment (schbetsy) [inline api/src/test/scala/hmda/api/http/InstitutionsHttpApiSpec.scala]: Is this the response we want? If a consumer of the api makes a request for a nonexistent institution, this response is misleading. I would think we want "Institution xxxxx not found".

I don't want to re-open this issue if it was already decided elsewhere, so let me know if there's discussion somewhere that I should refer to.

Comment (kgudel) [inline api/src/test/scala/hmda/api/http/InstitutionsHttpApiSpec.scala]: This would require adding more logic to the api which is not in the scope of this pr. It probably should be ticketed though.

**Comment by schbetsy** [comment]
LGTM. I'll draft a ticket for the error message comment I made.
