### PR TITLE
match Q613 and Q613-4

### LINKED ISSUE #2276: Calls to edits with name such as QXXX-XX fail
The regex [here](https://github.com/cfpb/hmda-platform/blob/master/hmda/src/main/scala/hmda/api/http/filing/submissions/EditsHttpApi.scala#L99) needs to be updated to account for edits such as Q615-1

### PR DESCRIPTION
**Pull request by omnipresent07**
Fix #2276 

From https://github.com/cfpb/hmda-platform/blob/master/common/src/main/resources/2018EditsDescriptions.txt I don't see `QXXX-XX` as mentioned in the bug. Please correct me if I'm wrong. 

Separate ticket opened https://github.com/cfpb/hmda-platform/issues/2277 to create spec for this class.

### CODE REVIEW

File: hmda/src/main/scala/hmda/api/http/filing/submissions/EditsHttpApi.scala [hunk 1]
```diff
@@ -96,7 +96,7 @@ trait EditsHttpApi extends HmdaTimeDirectives {
 
   //institutions/<institutionId>/filings/<period>/submissions/<submissionId>/edits/edit
   def editDetailsPath(oAuth2Authorization: OAuth2Authorization): Route = {
-    val editNameRegex: Regex = new Regex("""[SVQ]\d\d\d""")
+    val editNameRegex: Regex = new Regex("""[SVQ]\d\d\d(?:-\d)*""")
```
Comment (nickgrippin) [inline hmda/src/main/scala/hmda/api/http/filing/submissions/EditsHttpApi.scala]: This could probably be simplified to `(-\d)?`, we only want to match this pattern 0 or 1 times.

Comment (omnipresent07) [reply hmda/src/main/scala/hmda/api/http/filing/submissions/EditsHttpApi.scala]: `(?:)` forms a non-capturing group. Which, from my testing, seems to be necessary for Akka PatternMatcher DSL. without the `(?:)` we just get `-2` for `editName` when, for example, `Q613-2` get passed. I have however changed `*` to `?` to capture 0 or 1

Comment (nickgrippin) [reply hmda/src/main/scala/hmda/api/http/filing/submissions/EditsHttpApi.scala]: Nice, that sounds perfect! 👍
