### PR TITLE
Move OAuth inside the routes for Sign

### LINKED ISSUE #3399: Intermittent 405 Errors on sign
While testing we noticed intermittent 405 (method not allowed) errors while the UI did a POST on sign endpoint. Upon refreshing the page, at times, the error went away (UI got an expected 200 as opposed to 405). Due to the intermittent nature of the error, it was hard to reproduce. This error was also reproducible on the beta platform.

### PR DESCRIPTION
**Pull request by omnipresent07**
closes #3399 (maybe)

### CODE REVIEW

File: hmda/src/main/scala/hmda/api/http/filing/submissions/SignHttpApi.scala [hunk 1]
```diff
@@ -11,8 +11,9 @@ import akka.http.scaladsl.server.Directives._
 import akka.http.scaladsl.model.headers.RawHeader
 import akka.stream.ActorMaterializer
 import akka.util.Timeout
+import scala.concurrent.duration._
 import de.heikoseeberger.akkahttpcirce.FailFastCirceSupport._
-import io.circe.generic.auto._
+//import io.circe.generic.auto._
```
Comment (kgudel) [inline hmda/src/main/scala/hmda/api/http/filing/submissions/SignHttpApi.scala]: Probably best to just remove this import

**Comment by omnipresent07** [comment]
> Quick import removal comment, but looks good!

Fixed
