### PR TITLE
Fix SubmissionLarStats ActorRef

### LINKED ISSUE #970: Q130 is always failing in smoke tests

### PR DESCRIPTION
**Pull request by nickgrippin**
Closes #970

### CODE REVIEW

File: persistence/src/main/scala/hmda/persistence/processing/HmdaFileParser.scala [hunk 1]
```diff
@@ -56,23 +59,25 @@ object HmdaFileParser {
...
   import HmdaFileParser._
+  val duration = 10.seconds
+  implicit val timeout = Timeout(duration)
+  val config = ConfigFactory.load()
+  val flowParallelism = config.getInt("hmda.actor-flow-parallelism")
 
   var state = HmdaFileParseState()
   var encounteredParsingErrors: Boolean = false
-  val submissionLarStats = context.actorSelection(s"submission-lar-stats-${submissionId.toString}")
+  val supervisor = system.actorSelection("/user/supervisor")
```
Comment (jmarin) [inline persistence/src/main/scala/hmda/persistence/processing/HmdaFileParser.scala]: `HmdaFileParser` is a child of `HmdaSupervisor`. You can get the supervisor by doing `context.parent`, which gives you an `ActorRef`
