### PR TITLE
Return parsing errors

### LINKED ISSUE #629: GET all parser errors for an uploaded file
`/institutions/<institutionId>/filings/<period>/submissions/<submissionId>/parseErrors`
`GET` - List of each line of the submission that had parse errors, and the text of each error.
## Option 1

``` json
{
  "transmittalSheetErrors": [
    "Record Identifier is not an Integer",
    "Agency Code is not an Integer"
  ],
  "larErrors": [
    {
      "lineNumber": 2,
      "errorMessages": [
        "Incorrect number of fields. found: 32, expected: 39"
      ]
    },
    {
      "lineNumber": 4,
      "errorMessages": [
        "Record Identifier is not an Integer"
      ]
    },
    {
      "lineNumber": 11,
      "errorMessages": [
        "Loan Type is not an Integer",
        "Property Type is not an Integer",
        "Loan Purpose is not an Integer",
        "Owner Occupancy is not an Integer"
      ]
    }
  ]
}
```
- Pros: if the bank's file software has line numbers, it will be easy for them to find and correct errors.
- Cons: We are not currently persisting line number of each error, so we'd have to change how we persist errors. Adding line numbers may not be easy.
## Option 2

``` json
{
  "transmittalSheetErrors": {
    "line": "g|8800009923|t|201801171330|2017|99-0123456|412|FIRST TEST BANK|1275 First Street NE|Washington|DC|20002|FIRST BANK PARENT INC.|1700 G ST NW|WASHINGTON|DC|20552|Brian Jones|666-666-6666|555-555-5555|brian.jones@bank.com||||||||||||||||||",
    "errorMessages": [
      "Record Identifier is not an Integer",
      "Agency Code is not an Integer"
    ]
  },
  "larErrors": [
    {
      "line": "2|8800009923|3|8299422144|20170613|1|2|2|1|5|3|4|20170719|NA   |NA|NA |NA     |2|2|3| | | | |3| | | | |1|2|37|",
      "errorMessages": [
        "Incorrect number of fields. found: 32, expected: 39"
      ]
    },
    {
      "line": "t|8800009923|3|9471480396|20170919|1|1|2|1|40|3|4|20171018|NA   |45|067|950f.00|2|5|3| | | | |8| | | | |1|5|59|0| | | |NA   |2|1",
      "errorMessages": [
        "Record Identifier is not an Integer"
      ]
    },
    {
      "line": "2|8800009923|4|2185751597|20170328|n|h|c|d|25|3|3|20170425|NA   |45|067|9504.00|2|5|3| | | | |8| | | | |2|5|34|0| | | |NA   |2|1",
      "errorMessages": [
        "Loan Type is not an Integer",
        "Property Type is not an Integer",
        "Loan Purpose is not an Integer",
        "Owner Occupancy is not an Integer"
      ]
    }
  ]
}
```
- Pros: they can see the line they submitted and why it errors. They can use that to find and correct the errors in their files.
- Cons: In our current persistence model, each line's error set is not closely associated with its raw text. It might not be easy to figure out which line goes with which errors.

### PR DESCRIPTION
**Pull request by nickgrippin**
Closes #629

### CODE REVIEW

File: parser/shared/src/main/scala/hmda/parser/fi/lar/LarParsingError.scala [hunk 1]
```diff
@@ -0,0 +1,4 @@
+package hmda.parser.fi.lar
+
+case class LarParsingError(lineNumber: Int = 0, errorMessages: List[String] = List.empty)
+case class ParsingErrorSummary(transmittalSheetErrors: Seq[List[String]] = Seq.empty, larErrors: Seq[LarParsingError] = Seq.empty)
```
Comment (kgudel) [inline parser/shared/src/main/scala/hmda/parser/fi/lar/LarParsingError.scala]: I think that this can be a just a `transmittalSheetErrors: List[String]` and that would make it conform with the documentation added in `API.md`.

**Comment by kgudel** [comment]
Other than a small comment this one looks good!

File: parser/shared/src/main/scala/hmda/parser/fi/lar/LarParsingError.scala (hunk 1 above)
Comment (schbetsy) [inline parser/shared/src/main/scala/hmda/parser/fi/lar/LarParsingError.scala]: @kgudel is right. Currently the output doesn't quite match the documentation because there's an extra layer of `[]`s inside of `"transmittalSheetErrors"`, like so:
```json
  "transmittalSheetErrors": [
    [
      "Incorrect number of fields. found: 39, expected: 21"
    ]
  ],
```

Comment (nickgrippin) [inline parser/shared/src/main/scala/hmda/parser/fi/lar/LarParsingError.scala]: I had coded it this way to match the style originally in the `HmdaFileParseState`, but I do agree that it's superfluous.  I'll see if I can trim it down.

**Comment by kgudel** [comment]
LGTM!
