### PR TITLE
HMDA Analytics better exception handling on bad submission IDs

### LINKED ISSUE #4690: HMDA Analytics Better Exception Handling
Adjust the exception handling logic for better recovery when the HMDA Analytics service  encounters a malformed submission ID.

### PR DESCRIPTION
**Pull request by PatrickGoRaft**
closes #4690

### CODE REVIEW

File: hmda-analytics/src/main/scala/hmda/analytics/HmdaAnalyticsApp.scala [hunk 1]
```diff
@@ -428,37 +438,42 @@ object HmdaAnalyticsApp extends App with TransmittalSheetComponent with LarCompo
 
         _ <- deleteTsRow
         _ = if(tsDeletion)
-          log.info(s"Data removed from TS for  $submissionId ")
+          log.info(s"Attempt to remove data from TS table for  $submissionId  completed.")
         else
           log.info(s"Skipping Delete TS -- no deletion needed")
```
Comment (lchen-2101) [inline hmda-analytics/src/main/scala/hmda/analytics/HmdaAnalyticsApp.scala:443]: I feel like these logging messages should really be within the processing methods instead of a standalone block here, i.e. putting them in `deleteTsRow`, `deleteLarRows`, etc... thoughts?

Comment (lchen-2101) [reply hmda-analytics/src/main/scala/hmda/analytics/HmdaAnalyticsApp.scala:443]: or these can be something more generic like `deleteTsRow checkpoint`, but the actual informative messages be inside the process methods.

Comment (PatrickGoRaft) [reply hmda-analytics/src/main/scala/hmda/analytics/HmdaAnalyticsApp.scala:443]: i'll make these changes  this evening @lchen-2101

File: hmda-analytics/src/main/scala/hmda/analytics/HmdaAnalyticsApp.scala [hunk 2]
```diff
@@ -428,37 +438,42 @@ object HmdaAnalyticsApp extends App with TransmittalSheetComponent with LarCompo
...
+        _ = log.info(s"Attempt to add data to LAR table for  $submissionId  completed.")
+
 
         dateSigned   <- signDate
         _ = log.info(s"Date signed $dateSigned")
 
         res <- insertSubmissionHistory
         _ = if(historyInsertion)
-          log.info(s"Inserting into submission history")
+          log.info(s"Attempt to add data too Submission History Table for  $submissionId  completed.")
```
Comment (rkovalik-raft) [inline hmda-analytics/src/main/scala/hmda/analytics/HmdaAnalyticsApp.scala:464]: Nit pick typo: too -> to

File: hmda-analytics/src/main/scala/hmda/analytics/HmdaAnalyticsApp.scala [hunk 3]
```diff
@@ -428,37 +438,42 @@ object HmdaAnalyticsApp extends App with TransmittalSheetComponent with LarCompo
...
+        _ =  log.info(s"Attempt to add data to TS table for  $submissionId  completed.")
+
 
         _ <- insertLarRows
-        _ = log.info(s"Data added into LAR for  $submissionId")
+        _ = log.info(s"Attempt to add data to LAR table for  $submissionId  completed.")
+
 
         dateSigned   <- signDate
         _ = log.info(s"Date signed $dateSigned")
```
Comment (rkovalik-raft) [inline hmda-analytics/src/main/scala/hmda/analytics/HmdaAnalyticsApp.scala:460]: Should we add the `$submissionId` to this log as well?
