### PR TITLE
Fix clashing identifier

### LINKED ISSUE #1475: Snapshots failing to load
After uploading, parsing and validating a large file (seen on files 50k LARs and larger), when we hit the `/edits` endpoint, this happens in the logs:

```
[2018-02-01 22:18:04,003][WARN ][hmda_release-akka.actor.default-dispatcher-2] Failed to load snapshot [SnapshotMetadata(HmdaFileValidator-1576230-2017-3,52122,1517541305932)] (1 of 3), trying older one. Caused by: [java.lang.RuntimeException: Cannot deserialize this message: hmda.persistence.messages.commands.processing.HmdaFileValidatorState$HmdaVerificationState]
[2018-02-01 22:18:04,004][WARN ][hmda_release-akka.actor.default-dispatcher-2] Failed to load snapshot [SnapshotMetadata(HmdaFileValidator-1576230-2017-3,50340,1517541303247)] (2 of 3), trying older one. Caused by: [java.lang.RuntimeException: Cannot deserialize this message: hmda.persistence.messages.commands.processing.HmdaFileValidatorState$HmdaVerificationState]
[2018-02-01 22:18:04,007][WARN ][hmda_release-akka.actor.default-dispatcher-2] Failed to load snapshot [SnapshotMetadata(HmdaFileValidator-1576230-2017-3,47929,1517541298456)] (3 of 3), last attempt. Caused by: [java.lang.RuntimeException: Cannot deserialize this message: hmda.persistence.messages.commands.processing.HmdaFileValidatorState$HmdaVerificationState]
[2018-02-01 22:18:04,016][ERROR][hmda_release-akka.actor.default-dispatcher-3] Persistence failure when replaying events for persistenceId [HmdaFileValidator-1576230-2017-3]. Last known sequence number [0]
java.lang.RuntimeException: Cannot deserialize this message: hmda.persistence.messages.commands.processing.HmdaFileValidatorState$HmdaVerificationState
	at hmda.persistence.serialization.apor.APORProtobufSerializer.fromBinary(APORProtobufSerializer.scala:33)
	at akka.serialization.Serialization.deserializeByteArray(Serialization.scala:154)
	at akka.serialization.Serialization.$anonfun$deserialize$2(Serialization.scala:143)
	at scala.util.Try$.apply(Try.scala:209)
	at akka.serialization.Serialization.deserialize(Serialization.scala:137)
	at akka.persistence.cassandra.snapshot.CassandraSnapshotStore.$anonfun$load1Async$3(CassandraSnapshotStore.scala:152)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2018-02-01 22:18:14,010][ERROR][hmda_release-akka.actor.default-dispatcher-22] Ask timed out on [Actor[akka://hmda_release/user/supervisor/singleton/HmdaFileValidator-1576230-2017-3#1605643065]] after [10000 ms]. Sender[null] sent message of type "hmda.persistence.messages.CommonMessages$GetState$".
```

### PR DESCRIPTION
**Pull request by jmarin**
Closes #1475

### CODE REVIEW

File: persistence-model/src/main/scala/hmda/persistence/serialization/processing/HmdaFileValidatorStateProtobufSerializer.scala [hunk 1]
```diff
@@ -6,7 +6,7 @@ import HmdaFileValidatorStateProtobufConverter._
 import hmda.persistence.model.serialization.HmdaFileValidatorCommands.{ HmdaVerificationStateMessage, QMStateMessage, SVStateMessage }
 
 class HmdaFileValidatorStateProtobufSerializer extends SerializerWithStringManifest {
-  override def identifier: Int = 1011
+  override def identifier: Int = 1012
```
Comment (schbetsy) [inline persistence-model/src/main/scala/hmda/persistence/serialization/processing/HmdaFileValidatorStateProtobufSerializer.scala]: HmdaFilingView has 1012. Better do 1013 instead.
